### ISSUE TITLE
Adicionar o ckanext-datarequest

### ISSUE THREAD

**Issue by caduvieira** [dadosgovbr/ckanext-dadosgovbr#1]
https://github.com/conwetlab/ckanext-datarequests/

**Comment by augusto-herrmann** [comment]
Essa extensão serve para solicitar a publicação de dados que ainda não estão disponíveis. Para esse propósito o [Decreto 8.777/2016](http://www.lexml.gov.br/urn/urn:lex:br:federal:decreto:2016-05-11;8777), Capítulo IV, definiu que seria utilizado o [sistema e-SIC](https://esic.cgu.gov.br/) para fazer uma solicitação de acesso à informação para solicitar a abertura de novas bases de dados.

A referência ao e-SIC foi [implementada](https://github.com/dadosgovbr/ckanext-dadosgovbr/commit/8b69b64768ecfbf314000367c1259ab967d268cc) como uma mensagem que aparece no site, quando uma pesquisa não retorna resultados.
