### ISSUE TITLE
Renomear a extensão

### ISSUE THREAD

**Issue by augusto-herrmann** [dadosgovbr/ckanext-dadosgovbr#2]
O nome da extensão e do repositório, ckanext-dadosabertos, não reflete o propósito de existência desta extensão. Ela não é uma extensão para "adicionar dados abertos o CKAN", seja lá o que isso for, e sim para implementar o tema do Portal Brasileiro de Dados Abertos. Possíveis novos nomes:
* ckanext-dadosgovbr (esse repositório já existe e contém o tema anterior)
* ckanext-portalbrasileirodedadosabertos

**Comment by thenets** [comment]
Olá, Augusto.
O nome da extensão acabou não sendo alterada pois, quando eu tinha sido informado, faltava menos de uma semana para o deploy. Utilizei, na época, esse nome justamente por já existir uma extensão ckanext-dadosgovbr.
Vou, na próxima sprint, solicitar a alteração, que deve ocorrer junto com a alteração dos scripts de deploy.

**Comment by augusto-herrmann** [comment]
O repositório foi renomeado.
